#language to use in travis containers
language: python
python:
    - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov --disable-warnings
sudo: required

after_success: 
- coveralls